{{- if .Values.frontend.rollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: {{ .Values.frontend.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: frontend
          image: {{ .Values.images.frontend }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.frontend.port }}
          envFrom:
            - configMapRef: { name: frontend-config }
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: frontend
  strategy:
    blueGreen:
      activeService: frontend-active
      previewService: frontend-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 60
      steps:
        - setColor: green
        - pause: { duration: 30 }
        - setColor: blue
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-active
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
  selector:
    app: frontend
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-preview
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
  selector:
    app: frontend
  type: ClusterIP
{{- end }}
