---
# Defaults — paths (Ubuntu/Debian package defaults)
prometheus_config_dir: /etc/prometheus
prometheus_data_dir: /var/lib/prometheus
grafana_config_dir: /etc/grafana
grafana_data_dir: /var/lib/grafana
grafana_admin_user: admin
