# Ansible inventory - Generated by Terraform, do not edit manually
# ==================================================================

# Master node (kubeadm init)
[master]
${master_host.name} ansible_host=${master_host.public_ip} ansible_user=ubuntu ansible_ssh_private_key_file=${key_file} node_type=master

# Additional control-plane nodes (private subnet, reachable via bastion)
[workers]
%{ for w in worker_hosts ~}
${w.name} ansible_host=${w.private_ip} ansible_user=ubuntu ansible_ssh_private_key_file=${key_file} ansible_ssh_common_args='-o ForwardAgent=yes -o ProxyJump=ubuntu@${w.bastion}' node_type=master
%{ endfor ~}

# Ingress nodes (kubeadm join worker + label role=ingress)
[ingress]
%{ for ing in ingress_hosts ~}
${ing.name} ansible_host=${ing.public_ip} ansible_user=ubuntu ansible_ssh_private_key_file=${key_file} node_type=ingress
%{ endfor ~}

# Parent group: all K8s nodes
[k8s_cluster:children]
master
workers
ingress
