{
 "title": "TechShop Logs",
 "tags": [
  "techshop",
  "logs"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "🔵 Backend VM (shop-backend)",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{host=\"shop-backend\"}"
    }
   ]
  },
  {
   "title": "🟢 Frontend VM (shop-frontend)",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{host=\"shop-frontend\"}"
    }
   ]
  },
  {
   "title": "🟡 Database VM (shop-db)",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{host=\"shop-db\"}"
    }
   ]
  },
  {
   "title": "🟣 Monitor VM (shop-monitor)",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "{host=\"shop-monitor\"}"
    }
   ]
  }
 ]
}