apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: techshop
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: asia-southeast1-docker.pkg.dev/techshop-prod-2026/techshop/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
          resources: {}
