apiVersion: v1
data:
  FRONTEND_URL: https://8.233.56.51
  JWT_EXPIRES_IN: 7d
  NODE_ENV: production
  PORT: "1234"
kind: ConfigMap
metadata:
  creationTimestamp: "2026-07-07T06:59:05Z"
  name: backend-config
  namespace: techshop
  resourceVersion: "1783408511916239021"
  uid: 370dca8d-c191-4d36-8f87-efe64576c2ae
