apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["35.240.222.141"],"port":443,"protocol":"HTTPS","serviceName":"techshop:frontend","ingressName":"techshop:techshop-ingress","hostname":"techshop.local","path":"/","allNodes":false}]'
  creationTimestamp: "2026-07-07T04:51:28Z"
  generation: 2
  name: techshop-ingress
  namespace: techshop
  resourceVersion: "1783414610122095012"
  uid: c6f9dad5-90c8-4704-9dec-1eb27fe17bee
spec:
  ingressClassName: nginx
  rules:
  - host: techshop.local
    http:
      paths:
      - backend:
          service:
            name: frontend
            port:
              number: 3000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - techshop.local
    secretName: techshop-tls
status:
  loadBalancer:
    ingress:
    - ip: 35.240.222.141
