apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readonly-binding
  namespace: techshop
subjects:
  - kind: ServiceAccount
    name: readonly
    namespace: techshop
roleRef:
  kind: Role
  name: readonly-role
  apiGroup: rbac.authorization.k8s.io