apiVersion: v1
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOmd5NUx4ZFBpMkxOeUtPcWE4M0tBWXlKMkAxMC4yMC4xLjI6NTQzMi9zaG9wZGI/c2NoZW1hPXB1YmxpYw==
  JWT_SECRET: OGEzMGVhNmZkNWIyM2EwODU5ODgxM2IwYzg3ZDY4YmE2ZmU2NWFlOGUyM2NmMWZhZmYwNTBmOTZjMjY2NzE2YzEyOWM0MjUwZWVmYTFjYmNhNmNlMTQ4MDUwMmFkMmEyMmY0Mjc0ZGQ3N2Q4MjJjMjY2NGQ4MGUyYmZlOWE0Y2M=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"DATABASE_URL":"cG9zdGdyZXNxbDovL3Bvc3RncmVzOmd5NUx4ZFBpMkxOeUtPcWE4M0tBWXlKMkAxMC4yMC4xLjI6NTQzMi9zaG9wZGI/c2NoZW1hPXB1YmxpYw==","JWT_SECRET":"OGEzMGVhNmZkNWIyM2EwODU5ODgxM2IwYzg3ZDY4YmE2ZmU2NWFlOGUyM2NmMWZhZmYwNTBmOTZjMjY2NzE2YzEyOWM0MjUwZWVmYTFjYmNhNmNlMTQ4MDUwMmFkMmEyMmY0Mjc0ZGQ3N2Q4MjJjMjY2NGQ4MGUyYmZlOWE0Y2M="},"kind":"Secret","metadata":{"annotations":{},"name":"backend-secrets","namespace":"techshop"}}
  creationTimestamp: "2026-07-07T07:04:13Z"
  name: backend-secrets
  namespace: techshop
  resourceVersion: "1783411302354559018"
  uid: 0014e1d9-3a21-4b33-9b54-514044ecf78c
type: Opaque
