storage:
  ebsCSI:
    enabled: false       # StorageClass chỉ tạo 1 lần, dev đã tạo rồi

namespace: techshop-stg

images:
  backend: docker.io/vinh2504/deploy-web-backend:stg
  frontend: docker.io/vinh2504/deploy-web-frontend:stg

backend:
  replicas: 2

frontend:
  replicas: 2

config:
  nodeEnv: staging

ingress-nginx:
  enabled: false          # Dùng chung Ingress Controller với dev

ingress:
  className: nginx        # Dùng chung ingress class với dev
  host: stg.techshop.local

monitoring:
  loki:
    enabled: false
  promtail:
    enabled: false
