namespace: techshop-stg

images:
  backend: docker.io/vinh2504/deploy-web-backend:stg
  frontend: docker.io/vinh2504/deploy-web-frontend:stg

backend:
  replicas: 2

frontend:
  replicas: 2

config:
  nodeEnv: staging

ingress:
  host: stg.techshop.local

monitoring:
  loki:
    enabled: false
  promtail:
    enabled: false
