helm:
  parameters:
  - name: images.backend
    value: docker.io/vinh2504/deploy-web-backend:dev-4d7563b
    forcestring: true
  - name: images.frontend
    value: docker.io/vinh2504/deploy-web-frontend:dev-12c9c00
    forcestring: true
