helm:
  parameters:
  - name: images.backend
    value: docker.io/vinh2504/deploy-web-backend:dev
    forcestring: true
  - name: images.frontend
    value: docker.io/vinh2504/deploy-web-frontend:stg-f1844dc
    forcestring: true
