helm:
  parameters:
  - name: images.backend
    value: docker.io/vinh2504/deploy-web-backend:dev
    forcestring: true
  - name: images.frontend
    value: docker.io/vinh2504/deploy-web-frontend:dev-78d6205
    forcestring: true
