global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Monitor VM 
  - job_name: 'node-monitor'
    static_configs:
      - targets: ['127.0.0.1:9100']

  # Backend VM - node exporter trên backend
  - job_name: 'node-backend'
    static_configs:
      - targets: ['10.20.1.3:9100']

  # Frontend VM - node exporter trên frontend
  - job_name: 'node-frontend'
    static_configs:
      - targets: ['10.20.1.4:9100']

  # Database VM - node exporter trên database
  - job_name: 'node-db'
    static_configs:
      - targets: ['10.20.1.2:9100']