apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techshop-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=docker.io/vinh2504/deploy-web-backend,frontend=docker.io/vinh2504/deploy-web-frontend
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
    argocd-image-updater.argoproj.io/frontend.update-strategy: latest
    argocd-image-updater.argoproj.io/backend.force-update: "true"
    argocd-image-updater.argoproj.io/frontend.force-update: "true"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/vinh25042005/deploy-web.git
    targetRevision: capstone-week5
    path: helm/techshop
    helm:
      valueFiles:
        - values.yaml
        - env/values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: techshop-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
