apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techshop-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=docker.io/vinh2504/deploy-web-backend,frontend=docker.io/vinh2504/deploy-web-frontend
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-repository: https://github.com/vinh25042005/deploy-web.git
    argocd-image-updater.argoproj.io/git-branch: capstone-week5
    argocd-image-updater.argoproj.io/git-username: vinh25042005
    argocd-image-updater.argoproj.io/git-email: vinh2504@gmail.com
    argocd-image-updater.argoproj.io/backend.update-strategy: newest-build
    argocd-image-updater.argoproj.io/frontend.update-strategy: newest-build
    argocd-image-updater.argoproj.io/backend.force-update: "true"
    argocd-image-updater.argoproj.io/frontend.force-update: "true"
    argocd-image-updater.argoproj.io/backend.helm.image-spec: images.backend
    argocd-image-updater.argoproj.io/frontend.helm.image-spec: images.frontend
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/vinh25042005/deploy-web.git
    targetRevision: capstone-week5
    path: helm/techshop
    helm:
      valueFiles:
        - values.yaml
        - env/values-dev.yaml
      skipCrds: true
  destination:
    server: https://kubernetes.default.svc
    namespace: techshop-dev
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/replicas
        - /status
        - /spec/volumeClaimTemplates
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
